from app.models.teacher import Teacher
from app.models.student import Student
from app.models.course import Course
from app.models.classroom import Classroom
from app.models.period import Period
from app.models.section import Section
from app.models.prerequisite import Prerequisite
from app.models.student_situation import StudentSituation
from app.models.group import Group
from app.models.member import Member
from app.models.assessment import Assessment
from app.models.task import Task
from app.models.grade import Grade
from app.models.class_ import Class
