name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          ./venv/bin/pip install -r requirements.txt
          ./venv/bin/pip install pytest pytest-mock

      - name: Run tests
        run: |
          PYTHONPATH=. ./venv/bin/python -m pytest app/tests -v
