name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-mock

      - name: Set environment variables
        run: |
          echo "FLASK_ENV=testing" >> $GITHUB_ENV
          echo "DB_PASSWORD=test_password" >> $GITHUB_ENV

      - name: Run tests
        run: |
          PYTHONPATH=. pytest app/tests -v